### ISSUE TITLE
demo code for video?

### ISSUE THREAD

**Issue by dragen1860** [VIPL-Audio-Visual-Speech-Understanding/learn-an-effective-lip-reading-model-without-pains#13]
Dear author dalu:
  Thanks for sharing this simple but effective work. I just wonder will you share the demo code for inference a single video and visualize the result on screen. it would be greate helpful for the community. Thank you again.

**Comment by Fengdalu** [comment]
Please refer: https://github.com/VIPL-Audio-Visual-Speech-Understanding/LipNet-PyTorch/blob/master/demo.py
