### ISSUE TITLE
How to output the predicted word or sentence

### ISSUE THREAD

**Issue by John-McCartney** [VIPL-Audio-Visual-Speech-Understanding/learn-an-effective-lip-reading-model-without-pains#17]
Hello，dalu. II want to know how to output the predicted word or sentence. For example, whether it is right or wrong, it will output the predicted result 'about'. And how can I build my own test file with my own video？

**Comment by Fengdalu** [comment]
1. For LRW dataset, the predicted index matches the words in `label_sorted.txt', one word per line.
2. For you own video, please change it to a pkl file as [prepare_lrw.py](https://github.com/VIPL-Audio-Visual-Speech-Understanding/learn-an-effective-lip-reading-model-without-pains/blob/master/scripts/prepare_lrw.py)

**Comment by SE-Nickjackson** [comment]
> 

Have you solved this?
