### ISSUE TITLE
RuntimeWarning: Mean of empty slice.

### ISSUE THREAD

**Issue by Katerina0815** [VIPL-Audio-Visual-Speech-Understanding/learn-an-effective-lip-reading-model-without-pains#20]
load weights
loaded params/tot params:183/183
miss matched params: []
Start Testing, Data Length: 0
start testing

Hi, I already run the scripts/prepare_lrw1000.py and it generate LRW1000_Public_pkl_jpeg folder which has pkl files in trn,val and test. But still report this error

**Comment by Fengdalu** [comment]
Please check the data dictionaries: LRW1000_Public_pkl_jpeg/trn, LRW1000_Public_pkl_jpeg/val, LRW1000_Public_pkl_jpeg/tst.
